// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj3Wq7Ar-KNQy4YTS6c4hddvYN4__pCqM',
    appId: '1:923757663791:web:c40753f0114f34696e18da',
    messagingSenderId: '923757663791',
    projectId: 'hospital-appointment-3c916',
    authDomain: 'hospital-appointment-3c916.firebaseapp.com',
    storageBucket: 'hospital-appointment-3c916.appspot.com',
    measurementId: 'G-TTHGW080KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6KA9TvYHvD0TIkLglvfutxbs1wNh5-4o',
    appId: '1:923757663791:android:c343bc443f7ad73e6e18da',
    messagingSenderId: '923757663791',
    projectId: 'hospital-appointment-3c916',
    storageBucket: 'hospital-appointment-3c916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw3JEmI2CaPkpjWH44S8aIYpWrD1r5XLc',
    appId: '1:923757663791:ios:d02b99eab961799f6e18da',
    messagingSenderId: '923757663791',
    projectId: 'hospital-appointment-3c916',
    storageBucket: 'hospital-appointment-3c916.appspot.com',
    iosBundleId: 'com.example.hospitalBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw3JEmI2CaPkpjWH44S8aIYpWrD1r5XLc',
    appId: '1:923757663791:ios:d02b99eab961799f6e18da',
    messagingSenderId: '923757663791',
    projectId: 'hospital-appointment-3c916',
    storageBucket: 'hospital-appointment-3c916.appspot.com',
    iosBundleId: 'com.example.hospitalBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj3Wq7Ar-KNQy4YTS6c4hddvYN4__pCqM',
    appId: '1:923757663791:web:4260c75c4dd13c666e18da',
    messagingSenderId: '923757663791',
    projectId: 'hospital-appointment-3c916',
    authDomain: 'hospital-appointment-3c916.firebaseapp.com',
    storageBucket: 'hospital-appointment-3c916.appspot.com',
    measurementId: 'G-V5B8WS1FDY',
  );
}
